### ISSUE TITLE
Re-implement TeddyCloud with e.g. Python to attract more contributions?

### ISSUE THREAD

**Issue by jneuhauser** [toniebox-reverse-engineering/teddycloud#134]
Hello C dev's and non sophisticated C dev's,

I'm following TeddyCloud's development for quite some time, great work so far, but contributing to this C code base is not that easy, also as hobby C and Linux developer.

So I thought about how can we attract more people to create a beautiful Boxine cloud replacement for our lovely Tonieboxes.

So my question to this growing community is, does it make sense to re-implement TeddyCloud with a more easy programming language like Python?

Pro's:
- Attract more people to contribute
- Huge amount of libraries
- Direct code edit and execute for interpreted langs like Python

Con's:
- Doesn't run on MCUs like ESP32, etc.
- This C code base will get less attraction for contributions

**Comment by SciLor** [comment]
Hey,
thank you for your message. 

We decided to use C because of several problems:
* Especially the cc3200 based Toniebox uses an outdated TLS stack
    * Impossible to use with OpenSSL without changing system settings or using an outdates system
* Generating certificates with the special attributes needed is complicated with OpenSSL
    * Creating a certificate starting in the past needs dirty tricks like faketime to make it work

Beside python for ex. has several negative points:
* Regular updates of the language with breaking changes.
    * User needs to install a specific version for python
    * Regular maintaining fixes for those breaking changes
* Installing python can be a headache for non python users. 
* Dependencies can change and break things.
    * TLS doesn't work and supports different ciphers depending on the host system
    * Generated protobuf files may need updates

Besides that, we primarily need support on the frontend part. So people that understand React, for example.
